name: Actionlint

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.1.7
      - name: Check workflow files
        uses: ravsamhq/action-actionlint@1360a27665447978768d0623e6b9903c467946e8 # v0.1.0
